name: firstapp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [
              { "id": "anypoint-exchange", "username": "${{ secrets.ANYPOINT_USERNAME }}", "password": "${{ secrets.ANYPOINT_PASSWORD }}" }
            ]
          repositories: |
            [
              { "id": "local-repo", "url": "file:///${project.local-repo}" },
              { "id": "MuleRepository", "url": "https://repository.org/nexus-ee/content/repository/releases-ee/" },
              { "id": "anypoint-exchange", "url": "https://maven.anypoint.mulesoft.com/api/v2/maven" },
              { "id": "mulesoft-release", "url": "https://repository.mulesoft.org/releases" }
            ]

      - name: Show Maven settings
        run: cat ~/.m2/settings.xml

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          settings-path: ${{ github.workspace }}

      - name: Build and deploy to CloudHub
        run: mvn clean package deploy -DskipTests -DmuleDeploy -Dusername=${{ secrets.ANYPOINT_USERNAME }} -Dpassword=${{ secrets.ANYPOINT_PASSWORD }}

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,

          echo test, and deploy your project.
